"""Initial migration with all tables

Revision ID: 70973bc52058
Revises: 
Create Date: 2026-03-24 14:37:07.046435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70973bc52058'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cir_sections', 'node_id',
               existing_type=sa.VARCHAR(length=50),
               comment='节点ID',
               existing_nullable=False)
    op.alter_column('cir_sections', 'lesson_id',
               existing_type=sa.VARCHAR(length=50),
               comment='课件ID',
               existing_nullable=True)
    op.alter_column('cir_sections', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment='学校ID',
               existing_nullable=False)
    op.alter_column('cir_sections', 'node_name',
               existing_type=sa.VARCHAR(length=200),
               comment='节点标题',
               existing_nullable=False)
    op.alter_column('cir_sections', 'parent_id',
               existing_type=sa.VARCHAR(length=50),
               comment='父节点ID',
               existing_nullable=True)
    op.alter_column('cir_sections', 'node_type',
               existing_type=sa.VARCHAR(length=20),
               comment='节点类型：chapter/subchapter/point',
               existing_nullable=True)
    op.alter_column('cir_sections', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cir_sections', 'path',
               existing_type=sa.TEXT(),
               comment='节点路径（如 /chapter1/section2/point3）',
               existing_nullable=True)
    op.alter_column('cir_sections', 'page_num',
               existing_type=sa.INTEGER(),
               comment='对应PPT页码',
               existing_nullable=True)
    op.alter_column('cir_sections', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment='页面图片',
               existing_nullable=True)
    op.alter_column('cir_sections', 'bbox',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='答案高亮定位框 [x, y, w, h]',
               existing_nullable=True)
    op.alter_column('cir_sections', 'key_points',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='知识点',
               existing_nullable=True)
    op.alter_column('cir_sections', 'teaching_content',
               existing_type=sa.TEXT(),
               comment='教学内容',
               existing_nullable=True)
    op.alter_column('cir_sections', 'script_content',
               existing_type=sa.TEXT(),
               comment='讲稿内容',
               existing_nullable=True)
    op.alter_column('cir_sections', 'duration_seconds',
               existing_type=sa.INTEGER(),
               comment='时长（秒）',
               existing_nullable=True)
    op.alter_column('cir_sections', 'audio_url',
               existing_type=sa.VARCHAR(length=500),
               comment='音频URL',
               existing_nullable=True)
    op.alter_column('cir_sections', 'media_resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='媒体资源',
               existing_nullable=True)
    op.alter_column('cir_sections', 'is_teacher_edited',
               existing_type=sa.BOOLEAN(),
               comment='是否教师编辑过',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('course_categories', 'category_id',
               existing_type=sa.INTEGER(),
               comment='分类ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('course_categories_category_id_seq'::regclass)"))
    op.alter_column('course_categories', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment='学校ID，隔离',
               existing_nullable=False)
    op.alter_column('course_categories', 'category_name',
               existing_type=sa.VARCHAR(length=100),
               comment='分类名称',
               existing_nullable=False)
    op.alter_column('course_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('courses', 'course_id',
               existing_type=sa.VARCHAR(length=50),
               comment='课程ID',
               existing_nullable=False)
    op.alter_column('courses', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment='学校ID，隔离',
               existing_nullable=False)
    op.alter_column('courses', 'category_id',
               existing_type=sa.INTEGER(),
               comment='分类ID',
               existing_nullable=True)
    op.alter_column('courses', 'course_name',
               existing_type=sa.VARCHAR(length=200),
               comment='课程名称',
               existing_nullable=False)
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.VARCHAR(length=50),
               comment='教师ID',
               existing_nullable=True)
    op.alter_column('courses', 'term',
               existing_type=sa.VARCHAR(length=20),
               comment='学期',
               existing_nullable=True)
    op.alter_column('courses', 'ext_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='扩展信息',
               existing_nullable=True)
    op.alter_column('learning_progress', 'track_id',
               existing_type=sa.VARCHAR(length=50),
               comment='追踪ID',
               existing_nullable=False)
    op.alter_column('learning_progress', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               comment='用户ID',
               existing_nullable=True)
    op.alter_column('learning_progress', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               comment='会话ID，会话对齐',
               existing_nullable=False)
    op.alter_column('learning_progress', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment='学校ID',
               existing_nullable=False)
    op.alter_column('learning_progress', 'lesson_id',
               existing_type=sa.VARCHAR(length=50),
               comment='课件ID',
               existing_nullable=True)
    op.alter_column('learning_progress', 'current_node_id',
               existing_type=sa.VARCHAR(length=50),
               comment='断点节点ID',
               existing_nullable=True)
    op.alter_column('learning_progress', 'current_path',
               existing_type=sa.TEXT(),
               comment='当前学习路径',
               existing_nullable=True)
    op.alter_column('learning_progress', 'current_topic',
               existing_type=sa.TEXT(),
               comment='当前主题',
               existing_nullable=True)
    op.alter_column('learning_progress', 'last_qa_query',
               existing_type=sa.TEXT(),
               comment='最近一次有效问答',
               existing_nullable=True)
    op.alter_column('learning_progress', 'confusion_count',
               existing_type=sa.INTEGER(),
               comment='困惑计数，触发退回/补讲',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('learning_progress', 'mastery',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='主题掌握度映射（如 {"极限": 0.73}）',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('learning_progress', 'last_position_seconds',
               existing_type=sa.INTEGER(),
               comment='最后位置（秒）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('learning_progress', 'progress_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='进度百分比',
               existing_nullable=True)
    op.alter_column('learning_progress', 'adjust_type',
               existing_type=sa.VARCHAR(length=20),
               comment='调整类型',
               existing_nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('learning_progress', 'needs_supplement',
               existing_type=sa.BOOLEAN(),
               comment='是否需要补充学习',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('learning_progress', 'last_operate_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='最后操作时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lessons', 'lesson_id',
               existing_type=sa.VARCHAR(length=50),
               comment='课件ID，对应parseId',
               existing_nullable=False)
    op.alter_column('lessons', 'course_id',
               existing_type=sa.VARCHAR(length=50),
               comment='课程ID',
               existing_nullable=True)
    op.alter_column('lessons', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment='学校ID，隔离',
               existing_nullable=False)
    op.alter_column('lessons', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='标题',
               existing_nullable=False)
    op.alter_column('lessons', 'cover_image',
               existing_type=sa.VARCHAR(length=500),
               comment='封面图片',
               existing_nullable=True)
    op.alter_column('lessons', 'file_type',
               existing_type=sa.VARCHAR(length=10),
               comment='文件类型',
               existing_nullable=True)
    op.alter_column('lessons', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               comment='文件URL',
               existing_nullable=False)
    op.alter_column('lessons', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment='分类',
               existing_nullable=True)
    op.alter_column('lessons', 'task_status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态',
               existing_nullable=True,
               existing_server_default=sa.text("'processing'::character varying"))
    op.alter_column('lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lessons', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='完成时间',
               existing_nullable=True)
    op.alter_column('lessons', 'file_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='文件信息',
               existing_nullable=True)
    op.alter_column('qa_records', 'answer_id',
               existing_type=sa.INTEGER(),
               comment='回答ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('qa_records', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               comment='会话ID，相同会话代表多轮追问',
               existing_nullable=False)
    op.alter_column('qa_records', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               comment='用户ID',
               existing_nullable=True)
    op.alter_column('qa_records', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment='学校ID',
               existing_nullable=False)
    op.alter_column('qa_records', 'lesson_id',
               existing_type=sa.VARCHAR(length=50),
               comment='课件ID（允许为空）',
               existing_nullable=True)
    op.alter_column('qa_records', 'question_type',
               existing_type=sa.VARCHAR(length=10),
               comment='问题类型',
               existing_nullable=True)
    op.alter_column('qa_records', 'question_text',
               existing_type=sa.TEXT(),
               comment='问题内容',
               existing_nullable=False)
    op.alter_column('qa_records', 'answer_text',
               existing_type=sa.TEXT(),
               comment='回答内容',
               existing_nullable=False)
    op.alter_column('qa_records', 'cited_node_id',
               existing_type=sa.VARCHAR(length=50),
               comment='主引用节点ID',
               existing_nullable=True)
    op.alter_column('qa_records', 'source_page_num',
               existing_type=sa.INTEGER(),
               comment='主引用页码',
               existing_nullable=True)
    op.alter_column('qa_records', 'sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='多来源证据数组，包含bbox, score等前端高亮信息',
               existing_nullable=True)
    op.alter_column('qa_records', 'current_path',
               existing_type=sa.TEXT(),
               comment='提问时的学习路径',
               existing_nullable=True)
    op.alter_column('qa_records', 'video_timestamp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='播放器时间戳（秒），用于精准续接',
               existing_nullable=True)
    op.alter_column('qa_records', 'understanding_level',
               existing_type=sa.VARCHAR(length=20),
               comment='理解程度',
               existing_nullable=True)
    op.alter_column('qa_records', 'response_ms',
               existing_type=sa.INTEGER(),
               comment='响应时间（毫秒）',
               existing_nullable=True)
    op.alter_column('qa_records', 'is_accurate',
               existing_type=sa.BOOLEAN(),
               comment='是否准确',
               existing_nullable=True)
    op.alter_column('qa_records', 'reasoning_content',
               existing_type=sa.TEXT(),
               comment='reasoner的思考过程',
               existing_nullable=True)
    op.alter_column('qa_records', 'tool_calls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='工具调用记录（web_search等）',
               existing_nullable=True)
    op.alter_column('qa_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('users', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment='学校ID，多租户隔离',
               existing_nullable=False)
    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(length=20),
               comment='年级，如大一/2024级',
               existing_nullable=False)
    op.alter_column('users', 'major',
               existing_type=sa.VARCHAR(length=100),
               comment='专业',
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(length=100),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='角色：teacher/student')
    op.alter_column('users', 'contact_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='联系信息，JSON格式',
               existing_nullable=True)
    op.alter_column('users', 'profile_text',
               existing_type=sa.TEXT(),
               comment='用户补充说明（学习基础、目标等）',
               existing_nullable=True)
    op.alter_column('users', 'profile_ext',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='结构化画像扩展（兴趣、偏好交互模式等）',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'profile_ext',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='结构化画像扩展（兴趣、偏好交互模式等）',
               existing_nullable=True)
    op.alter_column('users', 'profile_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='用户补充说明（学习基础、目标等）',
               existing_nullable=True)
    op.alter_column('users', 'contact_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='联系信息，JSON格式',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='角色：teacher/student')
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('users', 'major',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='专业',
               existing_nullable=False)
    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='年级，如大一/2024级',
               existing_nullable=False)
    op.alter_column('users', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='学校ID，多租户隔离',
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('qa_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('qa_records', 'tool_calls',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='工具调用记录（web_search等）',
               existing_nullable=True)
    op.alter_column('qa_records', 'reasoning_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='reasoner的思考过程',
               existing_nullable=True)
    op.alter_column('qa_records', 'is_accurate',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否准确',
               existing_nullable=True)
    op.alter_column('qa_records', 'response_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='响应时间（毫秒）',
               existing_nullable=True)
    op.alter_column('qa_records', 'understanding_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='理解程度',
               existing_nullable=True)
    op.alter_column('qa_records', 'video_timestamp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='播放器时间戳（秒），用于精准续接',
               existing_nullable=True)
    op.alter_column('qa_records', 'current_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='提问时的学习路径',
               existing_nullable=True)
    op.alter_column('qa_records', 'sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='多来源证据数组，包含bbox, score等前端高亮信息',
               existing_nullable=True)
    op.alter_column('qa_records', 'source_page_num',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主引用页码',
               existing_nullable=True)
    op.alter_column('qa_records', 'cited_node_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='主引用节点ID',
               existing_nullable=True)
    op.alter_column('qa_records', 'answer_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='回答内容',
               existing_nullable=False)
    op.alter_column('qa_records', 'question_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='问题内容',
               existing_nullable=False)
    op.alter_column('qa_records', 'question_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='问题类型',
               existing_nullable=True)
    op.alter_column('qa_records', 'lesson_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='课件ID（允许为空）',
               existing_nullable=True)
    op.alter_column('qa_records', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='学校ID',
               existing_nullable=False)
    op.alter_column('qa_records', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=True)
    op.alter_column('qa_records', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='会话ID，相同会话代表多轮追问',
               existing_nullable=False)
    op.alter_column('qa_records', 'answer_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='回答ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('lessons', 'file_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='文件信息',
               existing_nullable=True)
    op.alter_column('lessons', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('lessons', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lessons', 'task_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='任务状态',
               existing_nullable=True,
               existing_server_default=sa.text("'processing'::character varying"))
    op.alter_column('lessons', 'category',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='分类',
               existing_nullable=True)
    op.alter_column('lessons', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='文件URL',
               existing_nullable=False)
    op.alter_column('lessons', 'file_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='文件类型',
               existing_nullable=True)
    op.alter_column('lessons', 'cover_image',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='封面图片',
               existing_nullable=True)
    op.alter_column('lessons', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='标题',
               existing_nullable=False)
    op.alter_column('lessons', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='学校ID，隔离',
               existing_nullable=False)
    op.alter_column('lessons', 'course_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='课程ID',
               existing_nullable=True)
    op.alter_column('lessons', 'lesson_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='课件ID，对应parseId',
               existing_nullable=False)
    op.alter_column('learning_progress', 'last_operate_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='最后操作时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('learning_progress', 'needs_supplement',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否需要补充学习',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('learning_progress', 'adjust_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='调整类型',
               existing_nullable=True,
               existing_server_default=sa.text("'normal'::character varying"))
    op.alter_column('learning_progress', 'progress_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='进度百分比',
               existing_nullable=True)
    op.alter_column('learning_progress', 'last_position_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='最后位置（秒）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('learning_progress', 'mastery',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='主题掌握度映射（如 {"极限": 0.73}）',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('learning_progress', 'confusion_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='困惑计数，触发退回/补讲',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('learning_progress', 'last_qa_query',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='最近一次有效问答',
               existing_nullable=True)
    op.alter_column('learning_progress', 'current_topic',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='当前主题',
               existing_nullable=True)
    op.alter_column('learning_progress', 'current_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='当前学习路径',
               existing_nullable=True)
    op.alter_column('learning_progress', 'current_node_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='断点节点ID',
               existing_nullable=True)
    op.alter_column('learning_progress', 'lesson_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='课件ID',
               existing_nullable=True)
    op.alter_column('learning_progress', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='学校ID',
               existing_nullable=False)
    op.alter_column('learning_progress', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='会话ID，会话对齐',
               existing_nullable=False)
    op.alter_column('learning_progress', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=True)
    op.alter_column('learning_progress', 'track_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='追踪ID',
               existing_nullable=False)
    op.alter_column('courses', 'ext_info',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展信息',
               existing_nullable=True)
    op.alter_column('courses', 'term',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='学期',
               existing_nullable=True)
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='教师ID',
               existing_nullable=True)
    op.alter_column('courses', 'course_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='课程名称',
               existing_nullable=False)
    op.alter_column('courses', 'category_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='分类ID',
               existing_nullable=True)
    op.alter_column('courses', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='学校ID，隔离',
               existing_nullable=False)
    op.alter_column('courses', 'course_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='课程ID',
               existing_nullable=False)
    op.alter_column('course_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('course_categories', 'category_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='分类名称',
               existing_nullable=False)
    op.alter_column('course_categories', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='学校ID，隔离',
               existing_nullable=False)
    op.alter_column('course_categories', 'category_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='分类ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('course_categories_category_id_seq'::regclass)"))
    op.alter_column('cir_sections', 'is_teacher_edited',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否教师编辑过',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('cir_sections', 'media_resources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='媒体资源',
               existing_nullable=True)
    op.alter_column('cir_sections', 'audio_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='音频URL',
               existing_nullable=True)
    op.alter_column('cir_sections', 'duration_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='时长（秒）',
               existing_nullable=True)
    op.alter_column('cir_sections', 'script_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='讲稿内容',
               existing_nullable=True)
    op.alter_column('cir_sections', 'teaching_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='教学内容',
               existing_nullable=True)
    op.alter_column('cir_sections', 'key_points',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='知识点',
               existing_nullable=True)
    op.alter_column('cir_sections', 'bbox',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='答案高亮定位框 [x, y, w, h]',
               existing_nullable=True)
    op.alter_column('cir_sections', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='页面图片',
               existing_nullable=True)
    op.alter_column('cir_sections', 'page_num',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='对应PPT页码',
               existing_nullable=True)
    op.alter_column('cir_sections', 'path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='节点路径（如 /chapter1/section2/point3）',
               existing_nullable=True)
    op.alter_column('cir_sections', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cir_sections', 'node_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='节点类型：chapter/subchapter/point',
               existing_nullable=True)
    op.alter_column('cir_sections', 'parent_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='父节点ID',
               existing_nullable=True)
    op.alter_column('cir_sections', 'node_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='节点标题',
               existing_nullable=False)
    op.alter_column('cir_sections', 'school_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='学校ID',
               existing_nullable=False)
    op.alter_column('cir_sections', 'lesson_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='课件ID',
               existing_nullable=True)
    op.alter_column('cir_sections', 'node_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='节点ID',
               existing_nullable=False)
    # ### end Alembic commands ###
